export const data = [
	{ id: 1, name: 'Hello reyfd' },
	{ id: 2, name: 'sello adadw' },
	{ id: 3, name: 'kello cbcxb' },
	{ id: 4, name: 'xollo zxc xc ' },
	{ id: 5, name: 'mollo  vbcbvc' },
	{ id: 7, name: 'nello ytutu' },
	{ id: 8, name: 'zello sdfe' },
	{ id: 9, name: 'asd AASD' },
	{ id: 10, name: 'qwer bdf' }, 
	{ id: 11, name: 'tyu cfg' },
	{ id: 12, name: 'iop arth' },
	{ id: 13, name: 'sello Mello' },
	{ id: 14, name: 'kello Mello' },
	{ id: 15, name: 'xollo Mello' },
	{ id: 17, name: 'werccs Mello' },
	{ id: 18, name: 'azaxc Mello' },
	{ id: 19, name: 'cvf Mello' },
	{ id: 20, name: 'bfgth Mello' },
	{ id: 21, name: 'puioyui Mello' }, 
	{ id: 22, name: 'ooo sdfdsllo' },
]